baseurl = "/"
relativeURLs = true

canonifyURLs = false
disableAliases = true
disableHugoGeneratorInject = true
# ignoreErrors = ["error-disable-taxonomy"]
# disableKinds = ["taxonomy", "term"]
removePathAccents = true
enableEmoji = true
enableGitInfo = false
enableRobotsTXT = true
languageCode = "fr-FR"
paginate = 24
rssLimit = 10
pygmentsUseClasses = true
pygmentsCodefences = true
defaultContentLanguage = "fr"

# add redirects/headers
[outputs]
  home = ["HTML", "RSS", "REDIRECTS", "HEADERS", "JSON"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
  suffixes = [""]
  delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true

[caches]
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "10s"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[taxonomies]
  category = "categories"
  regime = "regime" # Végé, sans-glut...
  ingredient = "ingredients"

  

[permalinks]
  blog = "/:title/"
  recettes = "/:title/"

[minify.tdewolff.html]
  keepWhitespace = false

[related]
  threshold = 80
  includeNewer = true
  toLower = false
    [[related.indices]]
    name = "categories"
    weight = 100
    [[related.indices]]
    name = "date"
    weight = 10


[markup.highlight]
      codeFences = true
      guessSyntax = true
      hl_Lines = ""
      lineNoStart = 1
      lineNos = true
      lineNumbersInTable = true
      tabWidth = 4
      style = "monokai"



# custom_css = ["assets/css/custom.css"]