backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
# for local cms developpement.
# Need to run : 'npx netlify-cms-proxy-server' from the root directory of the above repository.
local_backend: true

#By default, saving a post in the CMS interface pushes a commit directly to the publication branch specified in backend. However, you also have the option to enable the Editorial Workflow, which adds an interface for drafting, reviewing, and approving posts. To do this, add the following line to your Netlify CMS config.yml:
# This line should *not* be indented
# publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: /images
collections:
  - name: 'Recettes'
    label: 'Recettes'
    label-singular: 'Recette'
    folder: 'content/recettes'
    path: '{{type}}/{{slug}}/index'
    create: true
    fields:
      - {label: 'Intitulé', name: 'title', widget: 'string'}
      - {label: 'Brouillon', name: 'draft', widget: 'boolean', default: false}
      - {label: 'Image', name: 'img', widget: 'image', required: false}
      - {label: 'Description', name: 'description', widget: 'string', required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "recettes"}
      - label: "Catégorie"
        name: "type"
        widget: "select"
        default: "plat"
        options: 
          - { label : 'Entrée', value: 'entree'} 
          - { label : 'Plat', value : 'plat'}
          - { label: 'Dessert', value : 'dessert'}
      - label: "Sous-catégories"
        name: "recetteType"
        widget: "relation"
        collection: 'types-recettes'
        value_field: 'title'
        search_fields: ['title']
        multiple: true
        max: 4
        options_length: 5
        required: false
      - label: 'auteur'
        name: 'auteur'
        widget: 'string'
        required: false


        ## Description ##

      - {label : 'Régimes', name: 'regime',widget: "select", label_singular: 'Régime', required: false, multiple: true, options:  ['vegetarien', 'vegan', 'sans-glutten', 'sans-lactose']}
      - {label: 'Spécialité (région)', name: 'spécialité', widget: 'string', required: false}
      - label: 'Saison'
        name: 'saison'
        widget: 'select'
        multiple: true
        required: false
        options: 
          - {label : 'Printemps', value: 'printemps'}
          - { label : 'Eté', value: 'ete'}
          - { label : 'Automne', value: 'automne'}
          - { label : 'Hiver' , value: 'hiver'}
      - label : 'Servir chaud'
        name: 'temperature'
        widget: 'boolean'
        default: true
      
        ## Ingredients ##  

      - label: 'Ingredients'
        name: 'ingredients'
        widget: 'object'
        fields: 
          - label: 'Légumes ou fruits'
            name: 'legumes'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            collapsed: true
            fields: 
              - {label: 'Nom', name: 'title', widget: 'relation', collection: 'ingredients-legumes', value_field: 'title', search_fields: ['title'], options_length: 5}
              - {label: 'Quantité (nombre)', name: 'quantite', widget: 'number', value_type: 'float', hint: "Pour les décimales, utilisez des points et non des virgules. ex: 12.3 et non 12,3"}
              - {label: 'Unité (quantité en...)', name: 'unit', widget: 'select', options: ['Kg', 'grammes', 'unité']}
              - {label: 'Alergène', name: 'alergene', widget: 'boolean', required: false}
              - {label: 'commentaire', name: 'commentaire', widget: 'string', required: false}
         
          - label: 'Sec (Legumineuses, céréales)'
            name: 'sec'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            collapsed: true
            fields: 
              - {label: 'Nom', name: 'title', widget: 'relation', collection: 'ingredients-sec', value_field: 'title', search_fields: ['title'], options_length: 5}
              - {label: 'Quantité (nombre)', name: 'quantite', widget: 'number', value_type: 'float', hint: "Pour les décimales, utilisez des points et non des virgules. ex: 12.3 et non 12,3"}
              - {label: 'Unité (quantité en...)', name: 'unit', widget: 'select', options: ['Kg', 'grammes', 'unités']}
              - {label: 'Alergène', name: 'alergene', widget: 'boolean', required: false}
              - {label: 'commentaire', name: 'commentaire', widget: 'string', required: false}
        
          - label: 'Viandes et Poissons'
            name : 'animaux'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            fields:
              - {label: 'Nom', name: 'title', widget: 'relation', collection: 'ingredients-animaux', value_field: 'title', search_fields: ['title'], options_length: 5}  
              - {label: 'Quantité (nombre)', name: 'quantite', widget: 'number', value_type: 'float', hint: "Pour les décimales, utilisez des points et non des virgules. ex: 12.3 et non 12,3"}
              - {label: 'Unité (quantité en...)', name: 'unit', widget: 'select', options: ['Kg', 'grammes', 'unités']}
              - {label: 'commentaire', name: 'commentaire', widget: 'string', required: false}
        
          - label: 'Laitiers - oeuf - farines - gras...'
            name : 'lof'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            fields:
              - {label: 'Nom', name: 'title', widget: 'relation', collection: 'ingredients-lof', value_field: 'title', search_fields: ['title'], options_length: 5}  
              - {label: 'Quantité (nombre)', name: 'quantite', widget: 'number', value_type: 'float', hint: "Pour les décimales, utilisez des points et non des virgules. ex: 12.3 et non 12,3"}
              - {label: 'Unité (quantité en...)', name: 'unit', widget: 'select', options: ['Kg', 'grammes', 'unités', 'litre']}
              - {label: 'commentaire', name: 'commentaire', widget: 'string', required: false}
        
          - label: 'Sucrées'
            name : 'sucres'
            widget: 'list'
            hint: "Miel, biscuits..."
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            fields:
              - {label: 'Nom', name: 'title', widget: 'relation', collection: 'ingredients-lof', value_field: 'title', search_fields: ['title'], options_length: 5}  
              - {label: 'Quantité (nombre)', name: 'quantite', widget: 'number', value_type: 'float', hint: "Pour les décimales, utilisez des points et non des virgules. ex: 12.3 et non 12,3"}
              - {label: 'Unité (quantité en...)', name: 'unit', widget: 'select', options: ['Kg', 'grammes', 'unités', 'litre']}
              - {label: 'commentaire', name: 'commentaire', widget: 'string', required: false}
       
          - label: 'Autres'
            name : 'autres'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            fields:
              - {label: 'Noms', name: 'title', widget: 'relation', collection: 'ingredients-autres',value_field: 'title', search_fields: ['title'], options_length: 5 }  
              - {label: 'Quantité (nombre)', name: 'quantité', widget: 'number' ,value_type: 'float', hint: "Pour les décimales, utilisez des points et non des virgules. ex: 12.3 et non 12,3"}
              - {label: 'Unité (quantité en...)', name: 'unit', widget: 'select', options: ['Kg', 'grammes', 'litre', 'unités']}
              - {label: 'Alergène', name: 'alergene', widget: 'boolean', required: false}            
              - {label: 'commentaire', name: 'commentaire', widget: 'string', required: false}
          
          - label: 'Assaisonnement'
            name : 'epices'
            hint: 'Epices, sauces, condiments...'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            fields:
              - {label: 'Nom', name: 'title', widget: 'relation', collection: 'ingredients-assaisonnement', value_field: 'title', search_fields: ['title'], options_length: 5}            
              - {label: 'Quantité (nombre)', name: 'quantite', widget: 'number', value_type: 'float', hint: "Pour les décimales, utilisez des points et non des virgules. ex: 12.3 et non 12,3"}
              - {label: 'Unité (quantité en...)', name: 'unit', widget: 'select', options: ['Kg', 'grammes', 'litre', '']}
              - {label: 'Alergène', name: 'alergene', widget: 'boolean', required: false}
              - {label: 'commentaire', name: 'commentaire', widget: 'string', required: false}

      
      - label: 'Materiel'
        name: 'materiel'
        widget: 'list'
        allow_add: true
        add_to_top: true
        fields:
          - label: 'Nom'
            name: 'nom'
            widget: 'relation'
            collection: 'Materiel'
            value_field: 'nom'
            search_fields: ['nom']
            options_length: 5
    
      - label: 'Préparation'
        name: 'preparation'
        widget: 'markdown'
     
      - label: 'Astuces'
        name: 'astuces'
        widget: 'list'
        allow_add: true
        add_to_top: true
        label_singular: 'astuces'
        required: false
        fields: 
          - label: 'Astuce'
            name: 'astuce'
            widget: 'string'
      
      - label: "Date de publication"
        name: "publish_date"
        widget: "datetime"
        date_format: "DD-MM-YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
      

################################


    ### collections : INGREDIENTS ##########################

    # meta: 
    #  path:  
    #   widget: string
    #   label: 'Type'
    #   index_file: 'index' 

  - label: 'Ingredients - Legumes et fruits'
    name: 'ingredients-legumes'
    folder: content/ingredients/legumes_et_fruits
    path: '{{slug}}'
    create: true
    widget: 'list'
    allow-add: false
    fields: 
      - {label: 'Nom', name: 'title', widget: 'string'}
      - label: 'Saisons'
        name : 'saisons'
        hint : "...si l'ingrédient se trouvent surtout à certaines saisons"
        widget: 'select'
        multiple: true
        required: false
        options: 
          - {label : 'Printemps', value: 'printemps'}
          - { label : 'Eté', value: 'ete'}
          - { label : 'Automne', value: 'automne'}
          - { label : 'Hiver' , value: 'hiver'}
      - {label: 'Alergene', name: 'alergene', widget: boolean, default: false}
      - {label: 'Végétarien', name: 'vegetarien', widget: 'hidden', default: true}
      - {label: 'Végan', name: 'vegan', widget: 'hidden', default: true}
      - {label: 'Astuces', name: 'tips', widget: 'text', required: false}

  - label: 'Ingredients - Sec'
    name: 'ingredients-sec'
    folder: content/ingredients/ingredients-sec
    path: '{{slug}}'
    create: true
    widget: 'list'
    allow-add: false
    fields: 
      - { label: 'Nom', name: 'title', widget: 'string' }
      - label: 'Saisons'
        name : 'saisons'
        hint : "...si l'ingrédient se trouvent surtout à certaines saisons"
        widget: 'select'
        multiple: true
        required: false
        options: 
          - {label : 'Printemps', value: 'printemps'}
          - { label : 'Eté', value: 'ete'}
          - { label : 'Automne', value: 'automne'}
          - { label : 'Hiver' , value: 'hiver'}
      - {label: 'Alergene', name: 'alergene', widget: boolean, default: false}
      - {label: 'Gluten', name: 'gluten', widget: 'boolean', default: false}
      - {label: 'Végétarien', name: 'vegetarien', widget: 'boolean', default: true}
      - {label: 'Végan', name: 'vegan', widget: 'boolean', default: true}
      - {label: 'Astuces', name: 'tips', widget: 'text', required: false}

 

  - label: 'Ingredients - Laitiers, oeuf, farines, gras...'
    name: 'ingredients-lof'
    folder: content/ingredients/ingredients-lof
    path: '{{slug}}'
    create: true
    widget: 'list'
    allow-add: false
    fields: 
      - {label: 'Nom', name: 'title', widget: 'string'}
      - label: 'Saisons'
        name : 'saisons'
        hint : "...si l'ingrédient se trouvent surtout à certaines saisons"
        widget: 'select'
        multiple: true
        required: false
        options: 
          - {label : 'Printemps', value: 'printemps'}
          - { label : 'Eté', value: 'ete'}
          - { label : 'Automne', value: 'automne'}
          - { label : 'Hiver' , value: 'hiver'}
      - {label: 'Alergene', name: 'alergene', widget: boolean, default: false}
      - {label: 'Gluten', name: 'gluten', widget: 'boolean', default: false}
      - {label: 'Végétarien', name: 'vegetarien', widget: 'boolean', default: false}
      - {label: 'Végan', name: 'vegan', widget: 'boolean', default: false}
      - {label: 'Astuces', name: 'tips', widget: 'text', required: false}

  - label: 'Ingredients - Viandes et poissons'
    name: 'ingredients-animaux'
    folder: content/ingredients/ingredients-animaux
    path: '{{slug}}'
    create: true
    widget: 'list'
    allow-add: false
    summary: '{{fields.label}}'
    fields: 
      - {label: 'Nom', name: 'title', widget: 'string'}
      - label: 'Saisons'
        name : 'saisons'
        hint : "...si l'ingrédient se trouvent surtout à certaines saisons"
        widget: 'select'
        multiple: true
        required: false
        options: 
          - {label : 'Printemps', value: 'printemps'}
          - { label : 'Eté', value: 'ete'}
          - { label : 'Automne', value: 'automne'}
          - { label : 'Hiver' , value: 'hiver'}
      - {label: 'Alergene', name: 'alergene', widget: boolean, default: false}
      - {label: 'Gluten', name: 'gluten', widget: 'boolean', default: false}
      - {label: 'Végétarien', name: 'vegetarien', widget: 'hidden', default: false}
      - {label: 'Végan', name: 'vegan', widget: 'hidden', default: false}
      - {label: 'Astuces', name: 'tips', widget: 'text', required: false}

  - label: 'Ingredients - Sucrées'
    name: 'ingredients-sucres'
    folder: content/ingredients/ingredients-sucres
    path: '{{slug}}'
    create: true
    widget: 'list'
    allow-add: false
    summary: '{{fields.label}}'
    fields: 
      - {label: 'Nom', name: 'title', widget: 'string'}
      - label: 'Saisons'
        name : 'saisons'
        hint : "...si l'ingrédient se trouvent surtout à certaines saisons"
        widget: 'select'
        multiple: true
        required: false
        options: 
          - {label : 'Printemps', value: 'printemps'}
          - { label : 'Eté', value: 'ete'}
          - { label : 'Automne', value: 'automne'}
          - { label : 'Hiver' , value: 'hiver'}
      - {label: 'Alergene', name: 'alergene', widget: boolean, default: false}
      - {label: 'Gluten', name: 'gluten', widget: 'boolean', default: false}
      - {label: 'Végétarien', name: 'vegetarien', widget: 'boolean', default: false}
      - {label: 'Végan', name: 'vegan', widget: 'boolean', default: false}
      - {label: 'Astuces', name: 'tips', widget: 'text', required: false}
 
  - label: 'Ingredients - Assaisonnements'
    name: 'ingredients-assaisonnement'
    folder: content/ingredients/ingredients-assaisonnement
    path: '{{slug}}'
    create: true
    widget: 'list'
    allow-add: false
    summary: '{{fields.label}}'
    fields: 
      - {label: 'Nom', name: 'title', widget: 'string'}
      - label: 'Saisons'
        name : 'saisons'
        hint : "...si l'ingrédient se trouvent surtout à certaines saisons"
        widget: 'select'
        multiple: true
        required: false
        options: 
          - {label : 'Printemps', value: 'printemps'}
          - { label : 'Eté', value: 'ete'}
          - { label : 'Automne', value: 'automne'}
          - { label : 'Hiver' , value: 'hiver'}
      - {label: 'Alergene', name: 'alergene', widget: boolean, default: false}
      - {label: 'Gluten', name: 'gluten', widget: 'boolean', default: false}
      - {label: 'Végétarien', name: 'vegetarien', widget: 'boolean', default: false}
      - {label: 'Végan', name: 'vegan', widget: 'boolean', default: false}
      - {label: 'Astuces', name: 'tips', widget: 'text', required: false}

  - label: 'Ingredients - Autres'
    name: 'ingredients-autres'
    folder: content/ingredients/ingredients-autres
    path: '{{slug}}'
    create: true
    widget: 'list'
    allow-add: false
    summary: "{{fields.name}} - Ce qui n'est pas ailleurs"
    fields: 
      - {label: 'Nom', name: 'title', widget: 'string'}
      - label: 'Saisons'
        name : 'saisons'
        hint : "...si l'ingrédient se trouvent surtout à certaines saisons"
        widget: 'select'
        multiple: true
        required: false
        options: 
          - {label : 'Printemps', value: 'printemps'}
          - { label : 'Eté', value: 'ete'}
          - { label : 'Automne', value: 'automne'}
          - { label : 'Hiver' , value: 'hiver'}
      - {label: 'Alergene', name: 'alergene', widget: boolean, default: false}
      - {label: 'Gluten', name: 'gluten', widget: 'boolean', default: false}
      - {label: 'Végétarien', name: 'vegetarien', widget: 'boolean', default: false}
      - {label: 'Végan', name: 'vegan', widget: 'boolean', default: false}
      - {label: 'Astuces', name: 'tips', widget: 'text', required: false}

###########################
# recetteType
  - label: "sous-catégorie (Recettes)"
    name: 'types-recettes'
    folder: content/recetteType/
    path: '{{slug}}'
    create: true
    widget: 'list'
    fields:
      - {label: 'Nom', name: 'title', widget: 'string'}
      
          
          

