backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# when using the default proxy server port
# for local cms developpement.
# Need to run : 'npx netlify-cms-proxy-server' from the root directory of the above repository.
local_backend: true

#By default, saving a post in the CMS interface pushes a commit directly to the publication branch specified in backend. However, you also have the option to enable the Editorial Workflow, which adds an interface for drafting, reviewing, and approving posts. To do this, add the following line to your Netlify CMS config.yml:
# This line should *not* be indented
# publish_mode: editorial_workflow

media_folder: /images
public_folder: /images
collections:
  - name: 'recettes'
    label: 'recettes'
    label-singular: 'recette'
    folder: 'content/recettes/'
    nested:
      depth: 5
    create: true
    fields:
      - {label: 'Intitulé', name: 'title', widget: 'string'}
      - {label: 'Spécialité (région)', name: 'spécialité', widget: 'string', required: false}
      - {label: 'Image', name: 'image', widget: 'image',  default: "/static/images/plat.webp", required: false}
      - {label: 'Description', name: 'description', widget: 'string', required: false}
      - label: 'Ingredients'
        name: 'ingredients'
        widget: 'object'
        fields: 
          - label: 'Légumes ou fruits frais'
            name: 'frais'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular:  'Ingrédient'
            required: false
            collapsed: true
            fields: 
              - label: 'Nom'
                name: 'nom'
                widget: 'string'
              - label: 'Quantité'
                name: 'quantite'
                widget: 'number'
                value_type: 'float'
              - label: 'Poids'
                name: 'poids'
                widget: 'select'
                options: ['Kg', 'grammes', 'unité']
              - label: 'Alergène'
                name: 'alergene'
                widget: 'boolean'
                required: false
          - label: 'Sec (Legumineuses, céréales)'
            name: 'sec'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular:  'Ingrédient'
            required: false
            collapsed: true
            fields: 
              - label: 'Nom'
                name: 'nom'
                widget: 'string'
              - label: 'Quantité'
                name: 'quantite'
                widget: 'number'
                value_type: 'float'
              - label: 'Poids'
                name: 'poids'
                widget: 'select'
                options: ['Kg', 'grammes', 'unité']
              - label: 'Alergène'
                name: 'alergene'
                widget: 'boolean'
                required: false
          - label: 'Animaux'
            name : 'animaux'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            fields:
              - label: 'Nom'
                name: 'nom'
                widget: 'string'  #TODO? widget: relation            
              - label: 'Quantité'
                name: 'quantite'
                widget: 'number'
                value_type: 'float'
              - label: 'Poids'
                name: 'poids'
                widget: 'select'
                options: ['Kg', 'grammes', 'unité']
          - label: 'Autres'
            name : 'autres'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            fields:
              - label: 'Noms'
                name: 'noms'
                widget: 'string'  # widget: relation            
              - label: 'Quantité'
                name: 'quantité'
                widget: 'number'
                value_type: 'float'
              - label: 'Poids'
                name: 'poids'
                widget: 'select'
                options: ['Kg', 'grammes', 'litre', '']
              - label: 'Alergène'
                name: 'alergene'
                widget: 'boolean'
                required: false                 
          - label: 'Epices & condiments'
            name : 'epices'
            widget: 'list'
            allow_add: true
            add_to_top: true
            label_singular: 'Ingrédient'
            required: false
            fields:
              - label: 'Nom'
                name: 'nom'
                widget: 'string'  # widget: relation            
              - label: 'Quantité'
                name: 'quantite'
                widget: 'number'
                value_type: 'float'
                required: false
              - label: 'Poids'
                name: 'poids'
                widget: 'select'
                options: ['Kg', 'grammes', 'litre', '']
              - label: 'Alergène'
                name: 'alergene'
                widget: 'boolean'
                required: false
      - label: 'Materiel'
        name: 'materiel'
        widget: 'list'
        allow_add: true
        add_to_top: true
        fields:
          - label: 'Nom'
            name: 'nom'
            widget: 'string'
      - label: 'Préparation'
        name: 'preparation'
        widget: 'markdown'
      - label: 'Astuces'
        name: 'astuces'
        widget: 'list'
        allow_add: true
        add_to_top: true
        label_singular: 'astuces'
        required: false
        fields: 
          - label: 'Astuce'
            name: 'astuce'
            widget: 'string'

    meta: 
     path:  
      widget: string
      label: 'Type'
      index_file: '_index' 

  - label: 'Ingredients - Legumes et fruits'
    name: 'ingredients-legumes'
    folder: content/ingredients/legumes_et_fruits
    create: true
    widget: 'list'
    allow-add: false
    summary: '{{fields.name}} - {{fields.categorie}}'
    fields: 
      - {label: 'Nom', name: 'name', widget: 'string'}
      - {label: 'Categorie', name: 'categorie', widget: 'select', options: ['Frais','Animaux','Sec','Autre']}
      - {label: 'Alergene', name: 'alergene', widget: boolean, default: false}
      - {label: 'Astuces', name: 'tips', widget: 'text', required: false}



        
          
          

